apiVersion: v1
kind: Secret
metadata:
  name: pipeline-secrets
  namespace: video-pipeline
stringData:
  kafka_bootstrap: "b-1.optifyvideomsk.h80dv1.c3.kafka.ap-south-1.amazonaws.com:9094,b-2.optifyvideomsk.h80dv1.c3.kafka.ap-south-1.amazonaws.com:9094"
  s3_bucket: "optify-video-annotated-20251112-vb"
  aws_access_key_id: "REPLACE_ME"
  aws_secret_access_key: "REPLACE_ME"
