apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp-producer
  namespace: video-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtsp-producer
  template:
    metadata:
      labels:
        app: rtsp-producer
    spec:
      containers:
        - name: producer
          image: 929405966763.dkr.ecr.ap-south-1.amazonaws.com/producer-service:latest
          imagePullPolicy: Always
          env:
            - name: RTSP_URL
              value: rtsp://13.233.89.15:8554/mystream
            - name: KAFKA_BOOTSTRAP
              valueFrom:
                secretKeyRef:
                  name: pipeline-secrets
                  key: kafka_bootstrap
            - name: KAFKA_TOPIC
              value: video-ingest
            - name: BATCH_SIZE
              value: "25"
            - name: MAX_WIDTH
              value: "640"
            - name: JPEG_QUALITY
              value: "55"
            - name: KAFKA_SECURITY_PROTOCOL
              value: SSL
            - name: KAFKA_CA_FILE
              value: /etc/msk-certs/AmazonRootCA1.pem
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: msk-ca
              mountPath: /etc/msk-certs
              readOnly: true
      volumes:
        - name: msk-ca
          configMap:
            name: msk-ca-cert
